package com.ocp.rabbit.middleware.orm.model;

import java.io.Serializable;

/** 
 * 用于操作表:tb_guide_law_index
 * 功能描述:
 */
public class GuideLawIndex extends BaseModel implements Serializable {
    /**
     * hbase中存储的法律rowkey
     *
     * @mbg.generated
     */
    private String hbaseRowkey;

    /**
     * 条框项组合的id,前5位代表条，再3位代表款，再3位代表项，如00100001代表第一条第一款
     *
     * @mbg.generated
     */
    private String itemIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_guide_law_index
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law_index.hbase_rowkey
     *
     * @return the value of tb_guide_law_index.hbase_rowkey
     *
     * @mbg.generated
     */
    public String getHbaseRowkey() {
        return hbaseRowkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law_index.hbase_rowkey
     *
     * @param hbaseRowkey the value for tb_guide_law_index.hbase_rowkey
     *
     * @mbg.generated
     */
    public void setHbaseRowkey(String hbaseRowkey) {
        this.hbaseRowkey = hbaseRowkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law_index.item_index
     *
     * @return the value of tb_guide_law_index.item_index
     *
     * @mbg.generated
     */
    public String getItemIndex() {
        return itemIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law_index.item_index
     *
     * @param itemIndex the value for tb_guide_law_index.item_index
     *
     * @mbg.generated
     */
    public void setItemIndex(String itemIndex) {
        this.itemIndex = itemIndex;
    }
}