package com.ocp.rabbit.middleware.orm.model;

import java.io.Serializable;

public class GuideLawWithBLOBs extends GuideLaw implements Serializable {
  /**
  * 
  */
  private static final long serialVersionUID = 1L;

  /**
   * 法规标题
   *
   * @mbg.generated
   */
  private String lawName;

  /**
   * 来源名称，显示规定的名称
   *
   * @mbg.generated
   */
  private String sourceName;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tb_guide_law.law_name
   *
   * @return the value of tb_guide_law.law_name
   *
   * @mbg.generated
   */
  public String getLawName() {
    return lawName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tb_guide_law.law_name
   *
   * @param lawName the value for tb_guide_law.law_name
   *
   * @mbg.generated
   */
  public void setLawName(String lawName) {
    this.lawName = lawName;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tb_guide_law.source_name
   *
   * @return the value of tb_guide_law.source_name
   *
   * @mbg.generated
   */
  public String getSourceName() {
    return sourceName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tb_guide_law.source_name
   *
   * @param sourceName the value for tb_guide_law.source_name
   *
   * @mbg.generated
   */
  public void setSourceName(String sourceName) {
    this.sourceName = sourceName;
  }
}
