package com.ocp.rabbit.middleware.orm.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/** 
 * 用于操作表:tb_guide_law_index
 */
public class GuideLawIndexExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_guide_law_index
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_guide_law_index
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_guide_law_index
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_guide_law_index
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_guide_law_index
     *
     * @mbg.generated
     */
    private int startNum = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_guide_law_index
     *
     * @mbg.generated
     */
    private int endNum = 10;

    /**
     *
     * @mbg.generated
     */
    public GuideLawIndexExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *
     * @mbg.generated
     */
    public void setStartNum(int startNum) {
        this.startNum=startNum;
    }

    /**
     *
     * @mbg.generated
     */
    public int getStartNum() {
        return startNum;
    }

    /**
     *
     * @mbg.generated
     */
    public void setEndNum(int endNum) {
        this.endNum=endNum;
    }

    /**
     *
     * @mbg.generated
     */
    public int getEndNum() {
        return endNum - startNum;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_guide_law_index
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_guide_law_index
         *
         * @mbg.generated
         */
        private static final long serialVersionUID = 1L;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHbaseRowkeyIsNull() {
            addCriterion("hbase_rowkey is null");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyIsNotNull() {
            addCriterion("hbase_rowkey is not null");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyEqualTo(String value) {
            addCriterion("hbase_rowkey =", value, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyNotEqualTo(String value) {
            addCriterion("hbase_rowkey <>", value, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyGreaterThan(String value) {
            addCriterion("hbase_rowkey >", value, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyGreaterThanOrEqualTo(String value) {
            addCriterion("hbase_rowkey >=", value, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyLessThan(String value) {
            addCriterion("hbase_rowkey <", value, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyLessThanOrEqualTo(String value) {
            addCriterion("hbase_rowkey <=", value, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyLike(String value) {
            addCriterion("hbase_rowkey like", value, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyNotLike(String value) {
            addCriterion("hbase_rowkey not like", value, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyIn(List<String> values) {
            addCriterion("hbase_rowkey in", values, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyNotIn(List<String> values) {
            addCriterion("hbase_rowkey not in", values, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyBetween(String value1, String value2) {
            addCriterion("hbase_rowkey between", value1, value2, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyNotBetween(String value1, String value2) {
            addCriterion("hbase_rowkey not between", value1, value2, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andItemIndexIsNull() {
            addCriterion("item_index is null");
            return (Criteria) this;
        }

        public Criteria andItemIndexIsNotNull() {
            addCriterion("item_index is not null");
            return (Criteria) this;
        }

        public Criteria andItemIndexEqualTo(String value) {
            addCriterion("item_index =", value, "itemIndex");
            return (Criteria) this;
        }

        public Criteria andItemIndexNotEqualTo(String value) {
            addCriterion("item_index <>", value, "itemIndex");
            return (Criteria) this;
        }

        public Criteria andItemIndexGreaterThan(String value) {
            addCriterion("item_index >", value, "itemIndex");
            return (Criteria) this;
        }

        public Criteria andItemIndexGreaterThanOrEqualTo(String value) {
            addCriterion("item_index >=", value, "itemIndex");
            return (Criteria) this;
        }

        public Criteria andItemIndexLessThan(String value) {
            addCriterion("item_index <", value, "itemIndex");
            return (Criteria) this;
        }

        public Criteria andItemIndexLessThanOrEqualTo(String value) {
            addCriterion("item_index <=", value, "itemIndex");
            return (Criteria) this;
        }

        public Criteria andItemIndexLike(String value) {
            addCriterion("item_index like", value, "itemIndex");
            return (Criteria) this;
        }

        public Criteria andItemIndexNotLike(String value) {
            addCriterion("item_index not like", value, "itemIndex");
            return (Criteria) this;
        }

        public Criteria andItemIndexIn(List<String> values) {
            addCriterion("item_index in", values, "itemIndex");
            return (Criteria) this;
        }

        public Criteria andItemIndexNotIn(List<String> values) {
            addCriterion("item_index not in", values, "itemIndex");
            return (Criteria) this;
        }

        public Criteria andItemIndexBetween(String value1, String value2) {
            addCriterion("item_index between", value1, value2, "itemIndex");
            return (Criteria) this;
        }

        public Criteria andItemIndexNotBetween(String value1, String value2) {
            addCriterion("item_index not between", value1, value2, "itemIndex");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_guide_law_index
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_guide_law_index
         *
         * @mbg.generated
         */
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_guide_law_index
     *
     * @mbg.generated
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_guide_law_index
         *
         * @mbg.generated
         */
        private static final long serialVersionUID = 1L;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}