package com.ocp.rabbit.middleware.orm.model;

import java.io.Serializable;
import java.sql.Date;

/** 
 * 用于操作表:tb_guide_law
 * 功能描述:
 */
public class GuideLaw extends BaseModel implements Serializable {
    /**
     * id
     *
     * @mbg.generated
     */
    private String lawId;

    /**
     * HBase对应的行键，HBase表中数据与MySQL表中数据一一对应
     *
     * @mbg.generated
     */
    private String hbaseRowkey;

    /**
     * 法规文号
     *
     * @mbg.generated
     */
    private String lawNumber;

    /**
     * 法规等级，1:宪法;2:刑法，参照层级设计
     *
     * @mbg.generated
     */
    private Integer lawLevel;

    /**
     * 法条数目;法律法规包含的条数
     *
     * @mbg.generated
     */
    private Integer articleNumber;

    /**
     * 是否被修订，若为1，需要关联修订表
     *
     * @mbg.generated
     */
    private Integer isModified;

    /**
     * 发布日期
     *
     * @mbg.generated
     */
    private Date publicDate;

    /**
     * 实施日期;start
     *
     * @mbg.generated
     */
    private Date executeDate;

    /**
     * 修订日期，最近修订日期
     *
     * @mbg.generated
     */
    private Date modifiedDate;

    /**
     * 失效日期;end
     *
     * @mbg.generated
     */
    private Date outdateDate;

    /**
     * 发布部门
     *
     * @mbg.generated
     */
    private String publicDepartment;

    /**
     * 效力等级，部委规章等
     *
     * @mbg.generated
     */
    private String forceGrade;

    /**
     * 实效性，废止或正常
     *
     * @mbg.generated
     */
    private String timeliness;

    /**
     * 地方法规
     *
     * @mbg.generated
     */
    private String localLaw;

    /**
     * 裁判文书
     *
     * @mbg.generated
     */
    private String judgeDoc;

    /**
     * 行政法规
     *
     * @mbg.generated
     */
    private String adminLaw;

    /**
     * 部委文件
     *
     * @mbg.generated
     */
    private String governLaw;

    /**
     * 司法解释
     *
     * @mbg.generated
     */
    private String trailExplain;

    /**
     * 法律
     *
     * @mbg.generated
     */
    private String titleLaw;

    /**
     * 主id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     * 修改类型，1：修正案，2：修正大版本，3：人工合成大版本
     *
     * @mbg.generated
     */
    private Integer modifyType;

    /**
     * 来源id，
     *
     * @mbg.generated
     */
    private String sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_guide_law
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.law_id
     *
     * @return the value of tb_guide_law.law_id
     *
     * @mbg.generated
     */
    public String getLawId() {
        return lawId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.law_id
     *
     * @param lawId the value for tb_guide_law.law_id
     *
     * @mbg.generated
     */
    public void setLawId(String lawId) {
        this.lawId = lawId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.hbase_rowkey
     *
     * @return the value of tb_guide_law.hbase_rowkey
     *
     * @mbg.generated
     */
    public String getHbaseRowkey() {
        return hbaseRowkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.hbase_rowkey
     *
     * @param hbaseRowkey the value for tb_guide_law.hbase_rowkey
     *
     * @mbg.generated
     */
    public void setHbaseRowkey(String hbaseRowkey) {
        this.hbaseRowkey = hbaseRowkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.law_number
     *
     * @return the value of tb_guide_law.law_number
     *
     * @mbg.generated
     */
    public String getLawNumber() {
        return lawNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.law_number
     *
     * @param lawNumber the value for tb_guide_law.law_number
     *
     * @mbg.generated
     */
    public void setLawNumber(String lawNumber) {
        this.lawNumber = lawNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.law_level
     *
     * @return the value of tb_guide_law.law_level
     *
     * @mbg.generated
     */
    public Integer getLawLevel() {
        return lawLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.law_level
     *
     * @param lawLevel the value for tb_guide_law.law_level
     *
     * @mbg.generated
     */
    public void setLawLevel(Integer lawLevel) {
        this.lawLevel = lawLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.article_number
     *
     * @return the value of tb_guide_law.article_number
     *
     * @mbg.generated
     */
    public Integer getArticleNumber() {
        return articleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.article_number
     *
     * @param articleNumber the value for tb_guide_law.article_number
     *
     * @mbg.generated
     */
    public void setArticleNumber(Integer articleNumber) {
        this.articleNumber = articleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.is_modified
     *
     * @return the value of tb_guide_law.is_modified
     *
     * @mbg.generated
     */
    public Integer getIsModified() {
        return isModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.is_modified
     *
     * @param isModified the value for tb_guide_law.is_modified
     *
     * @mbg.generated
     */
    public void setIsModified(Integer isModified) {
        this.isModified = isModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.public_date
     *
     * @return the value of tb_guide_law.public_date
     *
     * @mbg.generated
     */
    public Date getPublicDate() {
        return publicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.public_date
     *
     * @param publicDate the value for tb_guide_law.public_date
     *
     * @mbg.generated
     */
    public void setPublicDate(Date publicDate) {
        this.publicDate = publicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.execute_date
     *
     * @return the value of tb_guide_law.execute_date
     *
     * @mbg.generated
     */
    public Date getExecuteDate() {
        return executeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.execute_date
     *
     * @param executeDate the value for tb_guide_law.execute_date
     *
     * @mbg.generated
     */
    public void setExecuteDate(Date executeDate) {
        this.executeDate = executeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.modified_date
     *
     * @return the value of tb_guide_law.modified_date
     *
     * @mbg.generated
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.modified_date
     *
     * @param modifiedDate the value for tb_guide_law.modified_date
     *
     * @mbg.generated
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.outdate_date
     *
     * @return the value of tb_guide_law.outdate_date
     *
     * @mbg.generated
     */
    public Date getOutdateDate() {
        return outdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.outdate_date
     *
     * @param outdateDate the value for tb_guide_law.outdate_date
     *
     * @mbg.generated
     */
    public void setOutdateDate(Date outdateDate) {
        this.outdateDate = outdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.public_department
     *
     * @return the value of tb_guide_law.public_department
     *
     * @mbg.generated
     */
    public String getPublicDepartment() {
        return publicDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.public_department
     *
     * @param publicDepartment the value for tb_guide_law.public_department
     *
     * @mbg.generated
     */
    public void setPublicDepartment(String publicDepartment) {
        this.publicDepartment = publicDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.force_grade
     *
     * @return the value of tb_guide_law.force_grade
     *
     * @mbg.generated
     */
    public String getForceGrade() {
        return forceGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.force_grade
     *
     * @param forceGrade the value for tb_guide_law.force_grade
     *
     * @mbg.generated
     */
    public void setForceGrade(String forceGrade) {
        this.forceGrade = forceGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.timeliness
     *
     * @return the value of tb_guide_law.timeliness
     *
     * @mbg.generated
     */
    public String getTimeliness() {
        return timeliness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.timeliness
     *
     * @param timeliness the value for tb_guide_law.timeliness
     *
     * @mbg.generated
     */
    public void setTimeliness(String timeliness) {
        this.timeliness = timeliness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.local_law
     *
     * @return the value of tb_guide_law.local_law
     *
     * @mbg.generated
     */
    public String getLocalLaw() {
        return localLaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.local_law
     *
     * @param localLaw the value for tb_guide_law.local_law
     *
     * @mbg.generated
     */
    public void setLocalLaw(String localLaw) {
        this.localLaw = localLaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.judge_doc
     *
     * @return the value of tb_guide_law.judge_doc
     *
     * @mbg.generated
     */
    public String getJudgeDoc() {
        return judgeDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.judge_doc
     *
     * @param judgeDoc the value for tb_guide_law.judge_doc
     *
     * @mbg.generated
     */
    public void setJudgeDoc(String judgeDoc) {
        this.judgeDoc = judgeDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.admin_law
     *
     * @return the value of tb_guide_law.admin_law
     *
     * @mbg.generated
     */
    public String getAdminLaw() {
        return adminLaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.admin_law
     *
     * @param adminLaw the value for tb_guide_law.admin_law
     *
     * @mbg.generated
     */
    public void setAdminLaw(String adminLaw) {
        this.adminLaw = adminLaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.govern_law
     *
     * @return the value of tb_guide_law.govern_law
     *
     * @mbg.generated
     */
    public String getGovernLaw() {
        return governLaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.govern_law
     *
     * @param governLaw the value for tb_guide_law.govern_law
     *
     * @mbg.generated
     */
    public void setGovernLaw(String governLaw) {
        this.governLaw = governLaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.trail_explain
     *
     * @return the value of tb_guide_law.trail_explain
     *
     * @mbg.generated
     */
    public String getTrailExplain() {
        return trailExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.trail_explain
     *
     * @param trailExplain the value for tb_guide_law.trail_explain
     *
     * @mbg.generated
     */
    public void setTrailExplain(String trailExplain) {
        this.trailExplain = trailExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.title_law
     *
     * @return the value of tb_guide_law.title_law
     *
     * @mbg.generated
     */
    public String getTitleLaw() {
        return titleLaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.title_law
     *
     * @param titleLaw the value for tb_guide_law.title_law
     *
     * @mbg.generated
     */
    public void setTitleLaw(String titleLaw) {
        this.titleLaw = titleLaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.parent_id
     *
     * @return the value of tb_guide_law.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.parent_id
     *
     * @param parentId the value for tb_guide_law.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.modify_type
     *
     * @return the value of tb_guide_law.modify_type
     *
     * @mbg.generated
     */
    public Integer getModifyType() {
        return modifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.modify_type
     *
     * @param modifyType the value for tb_guide_law.modify_type
     *
     * @mbg.generated
     */
    public void setModifyType(Integer modifyType) {
        this.modifyType = modifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guide_law.source_id
     *
     * @return the value of tb_guide_law.source_id
     *
     * @mbg.generated
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guide_law.source_id
     *
     * @param sourceId the value for tb_guide_law.source_id
     *
     * @mbg.generated
     */
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId;
    }
}