package com.ocp.rabbit.middleware.orm.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

/** 
 * 用于操作表:tb_guide_law
 */
public class GuideLawExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_guide_law
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_guide_law
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_guide_law
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_guide_law
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_guide_law
     *
     * @mbg.generated
     */
    private int startNum = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_guide_law
     *
     * @mbg.generated
     */
    private int endNum = 10;

    /**
     *
     * @mbg.generated
     */
    public GuideLawExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *
     * @mbg.generated
     */
    public void setStartNum(int startNum) {
        this.startNum=startNum;
    }

    /**
     *
     * @mbg.generated
     */
    public int getStartNum() {
        return startNum;
    }

    /**
     *
     * @mbg.generated
     */
    public void setEndNum(int endNum) {
        this.endNum=endNum;
    }

    /**
     *
     * @mbg.generated
     */
    public int getEndNum() {
        return endNum - startNum;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_guide_law
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_guide_law
         *
         * @mbg.generated
         */
        private static final long serialVersionUID = 1L;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andLawIdIsNull() {
            addCriterion("law_id is null");
            return (Criteria) this;
        }

        public Criteria andLawIdIsNotNull() {
            addCriterion("law_id is not null");
            return (Criteria) this;
        }

        public Criteria andLawIdEqualTo(String value) {
            addCriterion("law_id =", value, "lawId");
            return (Criteria) this;
        }

        public Criteria andLawIdNotEqualTo(String value) {
            addCriterion("law_id <>", value, "lawId");
            return (Criteria) this;
        }

        public Criteria andLawIdGreaterThan(String value) {
            addCriterion("law_id >", value, "lawId");
            return (Criteria) this;
        }

        public Criteria andLawIdGreaterThanOrEqualTo(String value) {
            addCriterion("law_id >=", value, "lawId");
            return (Criteria) this;
        }

        public Criteria andLawIdLessThan(String value) {
            addCriterion("law_id <", value, "lawId");
            return (Criteria) this;
        }

        public Criteria andLawIdLessThanOrEqualTo(String value) {
            addCriterion("law_id <=", value, "lawId");
            return (Criteria) this;
        }

        public Criteria andLawIdLike(String value) {
            addCriterion("law_id like", value, "lawId");
            return (Criteria) this;
        }

        public Criteria andLawIdNotLike(String value) {
            addCriterion("law_id not like", value, "lawId");
            return (Criteria) this;
        }

        public Criteria andLawIdIn(List<String> values) {
            addCriterion("law_id in", values, "lawId");
            return (Criteria) this;
        }

        public Criteria andLawIdNotIn(List<String> values) {
            addCriterion("law_id not in", values, "lawId");
            return (Criteria) this;
        }

        public Criteria andLawIdBetween(String value1, String value2) {
            addCriterion("law_id between", value1, value2, "lawId");
            return (Criteria) this;
        }

        public Criteria andLawIdNotBetween(String value1, String value2) {
            addCriterion("law_id not between", value1, value2, "lawId");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyIsNull() {
            addCriterion("hbase_rowkey is null");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyIsNotNull() {
            addCriterion("hbase_rowkey is not null");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyEqualTo(String value) {
            addCriterion("hbase_rowkey =", value, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyNotEqualTo(String value) {
            addCriterion("hbase_rowkey <>", value, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyGreaterThan(String value) {
            addCriterion("hbase_rowkey >", value, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyGreaterThanOrEqualTo(String value) {
            addCriterion("hbase_rowkey >=", value, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyLessThan(String value) {
            addCriterion("hbase_rowkey <", value, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyLessThanOrEqualTo(String value) {
            addCriterion("hbase_rowkey <=", value, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyLike(String value) {
            addCriterion("hbase_rowkey like", value, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyNotLike(String value) {
            addCriterion("hbase_rowkey not like", value, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyIn(List<String> values) {
            addCriterion("hbase_rowkey in", values, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyNotIn(List<String> values) {
            addCriterion("hbase_rowkey not in", values, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyBetween(String value1, String value2) {
            addCriterion("hbase_rowkey between", value1, value2, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andHbaseRowkeyNotBetween(String value1, String value2) {
            addCriterion("hbase_rowkey not between", value1, value2, "hbaseRowkey");
            return (Criteria) this;
        }

        public Criteria andLawNumberIsNull() {
            addCriterion("law_number is null");
            return (Criteria) this;
        }

        public Criteria andLawNumberIsNotNull() {
            addCriterion("law_number is not null");
            return (Criteria) this;
        }

        public Criteria andLawNumberEqualTo(String value) {
            addCriterion("law_number =", value, "lawNumber");
            return (Criteria) this;
        }

        public Criteria andLawNumberNotEqualTo(String value) {
            addCriterion("law_number <>", value, "lawNumber");
            return (Criteria) this;
        }

        public Criteria andLawNumberGreaterThan(String value) {
            addCriterion("law_number >", value, "lawNumber");
            return (Criteria) this;
        }

        public Criteria andLawNumberGreaterThanOrEqualTo(String value) {
            addCriterion("law_number >=", value, "lawNumber");
            return (Criteria) this;
        }

        public Criteria andLawNumberLessThan(String value) {
            addCriterion("law_number <", value, "lawNumber");
            return (Criteria) this;
        }

        public Criteria andLawNumberLessThanOrEqualTo(String value) {
            addCriterion("law_number <=", value, "lawNumber");
            return (Criteria) this;
        }

        public Criteria andLawNumberLike(String value) {
            addCriterion("law_number like", value, "lawNumber");
            return (Criteria) this;
        }

        public Criteria andLawNumberNotLike(String value) {
            addCriterion("law_number not like", value, "lawNumber");
            return (Criteria) this;
        }

        public Criteria andLawNumberIn(List<String> values) {
            addCriterion("law_number in", values, "lawNumber");
            return (Criteria) this;
        }

        public Criteria andLawNumberNotIn(List<String> values) {
            addCriterion("law_number not in", values, "lawNumber");
            return (Criteria) this;
        }

        public Criteria andLawNumberBetween(String value1, String value2) {
            addCriterion("law_number between", value1, value2, "lawNumber");
            return (Criteria) this;
        }

        public Criteria andLawNumberNotBetween(String value1, String value2) {
            addCriterion("law_number not between", value1, value2, "lawNumber");
            return (Criteria) this;
        }

        public Criteria andLawLevelIsNull() {
            addCriterion("law_level is null");
            return (Criteria) this;
        }

        public Criteria andLawLevelIsNotNull() {
            addCriterion("law_level is not null");
            return (Criteria) this;
        }

        public Criteria andLawLevelEqualTo(Integer value) {
            addCriterion("law_level =", value, "lawLevel");
            return (Criteria) this;
        }

        public Criteria andLawLevelNotEqualTo(Integer value) {
            addCriterion("law_level <>", value, "lawLevel");
            return (Criteria) this;
        }

        public Criteria andLawLevelGreaterThan(Integer value) {
            addCriterion("law_level >", value, "lawLevel");
            return (Criteria) this;
        }

        public Criteria andLawLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("law_level >=", value, "lawLevel");
            return (Criteria) this;
        }

        public Criteria andLawLevelLessThan(Integer value) {
            addCriterion("law_level <", value, "lawLevel");
            return (Criteria) this;
        }

        public Criteria andLawLevelLessThanOrEqualTo(Integer value) {
            addCriterion("law_level <=", value, "lawLevel");
            return (Criteria) this;
        }

        public Criteria andLawLevelIn(List<Integer> values) {
            addCriterion("law_level in", values, "lawLevel");
            return (Criteria) this;
        }

        public Criteria andLawLevelNotIn(List<Integer> values) {
            addCriterion("law_level not in", values, "lawLevel");
            return (Criteria) this;
        }

        public Criteria andLawLevelBetween(Integer value1, Integer value2) {
            addCriterion("law_level between", value1, value2, "lawLevel");
            return (Criteria) this;
        }

        public Criteria andLawLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("law_level not between", value1, value2, "lawLevel");
            return (Criteria) this;
        }

        public Criteria andArticleNumberIsNull() {
            addCriterion("article_number is null");
            return (Criteria) this;
        }

        public Criteria andArticleNumberIsNotNull() {
            addCriterion("article_number is not null");
            return (Criteria) this;
        }

        public Criteria andArticleNumberEqualTo(Integer value) {
            addCriterion("article_number =", value, "articleNumber");
            return (Criteria) this;
        }

        public Criteria andArticleNumberNotEqualTo(Integer value) {
            addCriterion("article_number <>", value, "articleNumber");
            return (Criteria) this;
        }

        public Criteria andArticleNumberGreaterThan(Integer value) {
            addCriterion("article_number >", value, "articleNumber");
            return (Criteria) this;
        }

        public Criteria andArticleNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("article_number >=", value, "articleNumber");
            return (Criteria) this;
        }

        public Criteria andArticleNumberLessThan(Integer value) {
            addCriterion("article_number <", value, "articleNumber");
            return (Criteria) this;
        }

        public Criteria andArticleNumberLessThanOrEqualTo(Integer value) {
            addCriterion("article_number <=", value, "articleNumber");
            return (Criteria) this;
        }

        public Criteria andArticleNumberIn(List<Integer> values) {
            addCriterion("article_number in", values, "articleNumber");
            return (Criteria) this;
        }

        public Criteria andArticleNumberNotIn(List<Integer> values) {
            addCriterion("article_number not in", values, "articleNumber");
            return (Criteria) this;
        }

        public Criteria andArticleNumberBetween(Integer value1, Integer value2) {
            addCriterion("article_number between", value1, value2, "articleNumber");
            return (Criteria) this;
        }

        public Criteria andArticleNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("article_number not between", value1, value2, "articleNumber");
            return (Criteria) this;
        }

        public Criteria andIsModifiedIsNull() {
            addCriterion("is_modified is null");
            return (Criteria) this;
        }

        public Criteria andIsModifiedIsNotNull() {
            addCriterion("is_modified is not null");
            return (Criteria) this;
        }

        public Criteria andIsModifiedEqualTo(Integer value) {
            addCriterion("is_modified =", value, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedNotEqualTo(Integer value) {
            addCriterion("is_modified <>", value, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedGreaterThan(Integer value) {
            addCriterion("is_modified >", value, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_modified >=", value, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedLessThan(Integer value) {
            addCriterion("is_modified <", value, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedLessThanOrEqualTo(Integer value) {
            addCriterion("is_modified <=", value, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedIn(List<Integer> values) {
            addCriterion("is_modified in", values, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedNotIn(List<Integer> values) {
            addCriterion("is_modified not in", values, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedBetween(Integer value1, Integer value2) {
            addCriterion("is_modified between", value1, value2, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedNotBetween(Integer value1, Integer value2) {
            addCriterion("is_modified not between", value1, value2, "isModified");
            return (Criteria) this;
        }

        public Criteria andPublicDateIsNull() {
            addCriterion("public_date is null");
            return (Criteria) this;
        }

        public Criteria andPublicDateIsNotNull() {
            addCriterion("public_date is not null");
            return (Criteria) this;
        }

        public Criteria andPublicDateEqualTo(Date value) {
            addCriterionForJDBCDate("public_date =", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("public_date <>", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateGreaterThan(Date value) {
            addCriterionForJDBCDate("public_date >", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("public_date >=", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateLessThan(Date value) {
            addCriterionForJDBCDate("public_date <", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("public_date <=", value, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateIn(List<Date> values) {
            addCriterionForJDBCDate("public_date in", values, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("public_date not in", values, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("public_date between", value1, value2, "publicDate");
            return (Criteria) this;
        }

        public Criteria andPublicDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("public_date not between", value1, value2, "publicDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateIsNull() {
            addCriterion("execute_date is null");
            return (Criteria) this;
        }

        public Criteria andExecuteDateIsNotNull() {
            addCriterion("execute_date is not null");
            return (Criteria) this;
        }

        public Criteria andExecuteDateEqualTo(Date value) {
            addCriterionForJDBCDate("execute_date =", value, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("execute_date <>", value, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateGreaterThan(Date value) {
            addCriterionForJDBCDate("execute_date >", value, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("execute_date >=", value, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateLessThan(Date value) {
            addCriterionForJDBCDate("execute_date <", value, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("execute_date <=", value, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateIn(List<Date> values) {
            addCriterionForJDBCDate("execute_date in", values, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("execute_date not in", values, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("execute_date between", value1, value2, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("execute_date not between", value1, value2, "executeDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNull() {
            addCriterion("modified_date is null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNotNull() {
            addCriterion("modified_date is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateEqualTo(Date value) {
            addCriterionForJDBCDate("modified_date =", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("modified_date <>", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThan(Date value) {
            addCriterionForJDBCDate("modified_date >", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("modified_date >=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThan(Date value) {
            addCriterionForJDBCDate("modified_date <", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("modified_date <=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIn(List<Date> values) {
            addCriterionForJDBCDate("modified_date in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("modified_date not in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("modified_date between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("modified_date not between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateIsNull() {
            addCriterion("outdate_date is null");
            return (Criteria) this;
        }

        public Criteria andOutdateDateIsNotNull() {
            addCriterion("outdate_date is not null");
            return (Criteria) this;
        }

        public Criteria andOutdateDateEqualTo(Date value) {
            addCriterionForJDBCDate("outdate_date =", value, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("outdate_date <>", value, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("outdate_date >", value, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("outdate_date >=", value, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateLessThan(Date value) {
            addCriterionForJDBCDate("outdate_date <", value, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("outdate_date <=", value, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateIn(List<Date> values) {
            addCriterionForJDBCDate("outdate_date in", values, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("outdate_date not in", values, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("outdate_date between", value1, value2, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("outdate_date not between", value1, value2, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andPublicDepartmentIsNull() {
            addCriterion("public_department is null");
            return (Criteria) this;
        }

        public Criteria andPublicDepartmentIsNotNull() {
            addCriterion("public_department is not null");
            return (Criteria) this;
        }

        public Criteria andPublicDepartmentEqualTo(String value) {
            addCriterion("public_department =", value, "publicDepartment");
            return (Criteria) this;
        }

        public Criteria andPublicDepartmentNotEqualTo(String value) {
            addCriterion("public_department <>", value, "publicDepartment");
            return (Criteria) this;
        }

        public Criteria andPublicDepartmentGreaterThan(String value) {
            addCriterion("public_department >", value, "publicDepartment");
            return (Criteria) this;
        }

        public Criteria andPublicDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("public_department >=", value, "publicDepartment");
            return (Criteria) this;
        }

        public Criteria andPublicDepartmentLessThan(String value) {
            addCriterion("public_department <", value, "publicDepartment");
            return (Criteria) this;
        }

        public Criteria andPublicDepartmentLessThanOrEqualTo(String value) {
            addCriterion("public_department <=", value, "publicDepartment");
            return (Criteria) this;
        }

        public Criteria andPublicDepartmentLike(String value) {
            addCriterion("public_department like", value, "publicDepartment");
            return (Criteria) this;
        }

        public Criteria andPublicDepartmentNotLike(String value) {
            addCriterion("public_department not like", value, "publicDepartment");
            return (Criteria) this;
        }

        public Criteria andPublicDepartmentIn(List<String> values) {
            addCriterion("public_department in", values, "publicDepartment");
            return (Criteria) this;
        }

        public Criteria andPublicDepartmentNotIn(List<String> values) {
            addCriterion("public_department not in", values, "publicDepartment");
            return (Criteria) this;
        }

        public Criteria andPublicDepartmentBetween(String value1, String value2) {
            addCriterion("public_department between", value1, value2, "publicDepartment");
            return (Criteria) this;
        }

        public Criteria andPublicDepartmentNotBetween(String value1, String value2) {
            addCriterion("public_department not between", value1, value2, "publicDepartment");
            return (Criteria) this;
        }

        public Criteria andForceGradeIsNull() {
            addCriterion("force_grade is null");
            return (Criteria) this;
        }

        public Criteria andForceGradeIsNotNull() {
            addCriterion("force_grade is not null");
            return (Criteria) this;
        }

        public Criteria andForceGradeEqualTo(String value) {
            addCriterion("force_grade =", value, "forceGrade");
            return (Criteria) this;
        }

        public Criteria andForceGradeNotEqualTo(String value) {
            addCriterion("force_grade <>", value, "forceGrade");
            return (Criteria) this;
        }

        public Criteria andForceGradeGreaterThan(String value) {
            addCriterion("force_grade >", value, "forceGrade");
            return (Criteria) this;
        }

        public Criteria andForceGradeGreaterThanOrEqualTo(String value) {
            addCriterion("force_grade >=", value, "forceGrade");
            return (Criteria) this;
        }

        public Criteria andForceGradeLessThan(String value) {
            addCriterion("force_grade <", value, "forceGrade");
            return (Criteria) this;
        }

        public Criteria andForceGradeLessThanOrEqualTo(String value) {
            addCriterion("force_grade <=", value, "forceGrade");
            return (Criteria) this;
        }

        public Criteria andForceGradeLike(String value) {
            addCriterion("force_grade like", value, "forceGrade");
            return (Criteria) this;
        }

        public Criteria andForceGradeNotLike(String value) {
            addCriterion("force_grade not like", value, "forceGrade");
            return (Criteria) this;
        }

        public Criteria andForceGradeIn(List<String> values) {
            addCriterion("force_grade in", values, "forceGrade");
            return (Criteria) this;
        }

        public Criteria andForceGradeNotIn(List<String> values) {
            addCriterion("force_grade not in", values, "forceGrade");
            return (Criteria) this;
        }

        public Criteria andForceGradeBetween(String value1, String value2) {
            addCriterion("force_grade between", value1, value2, "forceGrade");
            return (Criteria) this;
        }

        public Criteria andForceGradeNotBetween(String value1, String value2) {
            addCriterion("force_grade not between", value1, value2, "forceGrade");
            return (Criteria) this;
        }

        public Criteria andTimelinessIsNull() {
            addCriterion("timeliness is null");
            return (Criteria) this;
        }

        public Criteria andTimelinessIsNotNull() {
            addCriterion("timeliness is not null");
            return (Criteria) this;
        }

        public Criteria andTimelinessEqualTo(String value) {
            addCriterion("timeliness =", value, "timeliness");
            return (Criteria) this;
        }

        public Criteria andTimelinessNotEqualTo(String value) {
            addCriterion("timeliness <>", value, "timeliness");
            return (Criteria) this;
        }

        public Criteria andTimelinessGreaterThan(String value) {
            addCriterion("timeliness >", value, "timeliness");
            return (Criteria) this;
        }

        public Criteria andTimelinessGreaterThanOrEqualTo(String value) {
            addCriterion("timeliness >=", value, "timeliness");
            return (Criteria) this;
        }

        public Criteria andTimelinessLessThan(String value) {
            addCriterion("timeliness <", value, "timeliness");
            return (Criteria) this;
        }

        public Criteria andTimelinessLessThanOrEqualTo(String value) {
            addCriterion("timeliness <=", value, "timeliness");
            return (Criteria) this;
        }

        public Criteria andTimelinessLike(String value) {
            addCriterion("timeliness like", value, "timeliness");
            return (Criteria) this;
        }

        public Criteria andTimelinessNotLike(String value) {
            addCriterion("timeliness not like", value, "timeliness");
            return (Criteria) this;
        }

        public Criteria andTimelinessIn(List<String> values) {
            addCriterion("timeliness in", values, "timeliness");
            return (Criteria) this;
        }

        public Criteria andTimelinessNotIn(List<String> values) {
            addCriterion("timeliness not in", values, "timeliness");
            return (Criteria) this;
        }

        public Criteria andTimelinessBetween(String value1, String value2) {
            addCriterion("timeliness between", value1, value2, "timeliness");
            return (Criteria) this;
        }

        public Criteria andTimelinessNotBetween(String value1, String value2) {
            addCriterion("timeliness not between", value1, value2, "timeliness");
            return (Criteria) this;
        }

        public Criteria andLocalLawIsNull() {
            addCriterion("local_law is null");
            return (Criteria) this;
        }

        public Criteria andLocalLawIsNotNull() {
            addCriterion("local_law is not null");
            return (Criteria) this;
        }

        public Criteria andLocalLawEqualTo(String value) {
            addCriterion("local_law =", value, "localLaw");
            return (Criteria) this;
        }

        public Criteria andLocalLawNotEqualTo(String value) {
            addCriterion("local_law <>", value, "localLaw");
            return (Criteria) this;
        }

        public Criteria andLocalLawGreaterThan(String value) {
            addCriterion("local_law >", value, "localLaw");
            return (Criteria) this;
        }

        public Criteria andLocalLawGreaterThanOrEqualTo(String value) {
            addCriterion("local_law >=", value, "localLaw");
            return (Criteria) this;
        }

        public Criteria andLocalLawLessThan(String value) {
            addCriterion("local_law <", value, "localLaw");
            return (Criteria) this;
        }

        public Criteria andLocalLawLessThanOrEqualTo(String value) {
            addCriterion("local_law <=", value, "localLaw");
            return (Criteria) this;
        }

        public Criteria andLocalLawLike(String value) {
            addCriterion("local_law like", value, "localLaw");
            return (Criteria) this;
        }

        public Criteria andLocalLawNotLike(String value) {
            addCriterion("local_law not like", value, "localLaw");
            return (Criteria) this;
        }

        public Criteria andLocalLawIn(List<String> values) {
            addCriterion("local_law in", values, "localLaw");
            return (Criteria) this;
        }

        public Criteria andLocalLawNotIn(List<String> values) {
            addCriterion("local_law not in", values, "localLaw");
            return (Criteria) this;
        }

        public Criteria andLocalLawBetween(String value1, String value2) {
            addCriterion("local_law between", value1, value2, "localLaw");
            return (Criteria) this;
        }

        public Criteria andLocalLawNotBetween(String value1, String value2) {
            addCriterion("local_law not between", value1, value2, "localLaw");
            return (Criteria) this;
        }

        public Criteria andJudgeDocIsNull() {
            addCriterion("judge_doc is null");
            return (Criteria) this;
        }

        public Criteria andJudgeDocIsNotNull() {
            addCriterion("judge_doc is not null");
            return (Criteria) this;
        }

        public Criteria andJudgeDocEqualTo(String value) {
            addCriterion("judge_doc =", value, "judgeDoc");
            return (Criteria) this;
        }

        public Criteria andJudgeDocNotEqualTo(String value) {
            addCriterion("judge_doc <>", value, "judgeDoc");
            return (Criteria) this;
        }

        public Criteria andJudgeDocGreaterThan(String value) {
            addCriterion("judge_doc >", value, "judgeDoc");
            return (Criteria) this;
        }

        public Criteria andJudgeDocGreaterThanOrEqualTo(String value) {
            addCriterion("judge_doc >=", value, "judgeDoc");
            return (Criteria) this;
        }

        public Criteria andJudgeDocLessThan(String value) {
            addCriterion("judge_doc <", value, "judgeDoc");
            return (Criteria) this;
        }

        public Criteria andJudgeDocLessThanOrEqualTo(String value) {
            addCriterion("judge_doc <=", value, "judgeDoc");
            return (Criteria) this;
        }

        public Criteria andJudgeDocLike(String value) {
            addCriterion("judge_doc like", value, "judgeDoc");
            return (Criteria) this;
        }

        public Criteria andJudgeDocNotLike(String value) {
            addCriterion("judge_doc not like", value, "judgeDoc");
            return (Criteria) this;
        }

        public Criteria andJudgeDocIn(List<String> values) {
            addCriterion("judge_doc in", values, "judgeDoc");
            return (Criteria) this;
        }

        public Criteria andJudgeDocNotIn(List<String> values) {
            addCriterion("judge_doc not in", values, "judgeDoc");
            return (Criteria) this;
        }

        public Criteria andJudgeDocBetween(String value1, String value2) {
            addCriterion("judge_doc between", value1, value2, "judgeDoc");
            return (Criteria) this;
        }

        public Criteria andJudgeDocNotBetween(String value1, String value2) {
            addCriterion("judge_doc not between", value1, value2, "judgeDoc");
            return (Criteria) this;
        }

        public Criteria andAdminLawIsNull() {
            addCriterion("admin_law is null");
            return (Criteria) this;
        }

        public Criteria andAdminLawIsNotNull() {
            addCriterion("admin_law is not null");
            return (Criteria) this;
        }

        public Criteria andAdminLawEqualTo(String value) {
            addCriterion("admin_law =", value, "adminLaw");
            return (Criteria) this;
        }

        public Criteria andAdminLawNotEqualTo(String value) {
            addCriterion("admin_law <>", value, "adminLaw");
            return (Criteria) this;
        }

        public Criteria andAdminLawGreaterThan(String value) {
            addCriterion("admin_law >", value, "adminLaw");
            return (Criteria) this;
        }

        public Criteria andAdminLawGreaterThanOrEqualTo(String value) {
            addCriterion("admin_law >=", value, "adminLaw");
            return (Criteria) this;
        }

        public Criteria andAdminLawLessThan(String value) {
            addCriterion("admin_law <", value, "adminLaw");
            return (Criteria) this;
        }

        public Criteria andAdminLawLessThanOrEqualTo(String value) {
            addCriterion("admin_law <=", value, "adminLaw");
            return (Criteria) this;
        }

        public Criteria andAdminLawLike(String value) {
            addCriterion("admin_law like", value, "adminLaw");
            return (Criteria) this;
        }

        public Criteria andAdminLawNotLike(String value) {
            addCriterion("admin_law not like", value, "adminLaw");
            return (Criteria) this;
        }

        public Criteria andAdminLawIn(List<String> values) {
            addCriterion("admin_law in", values, "adminLaw");
            return (Criteria) this;
        }

        public Criteria andAdminLawNotIn(List<String> values) {
            addCriterion("admin_law not in", values, "adminLaw");
            return (Criteria) this;
        }

        public Criteria andAdminLawBetween(String value1, String value2) {
            addCriterion("admin_law between", value1, value2, "adminLaw");
            return (Criteria) this;
        }

        public Criteria andAdminLawNotBetween(String value1, String value2) {
            addCriterion("admin_law not between", value1, value2, "adminLaw");
            return (Criteria) this;
        }

        public Criteria andGovernLawIsNull() {
            addCriterion("govern_law is null");
            return (Criteria) this;
        }

        public Criteria andGovernLawIsNotNull() {
            addCriterion("govern_law is not null");
            return (Criteria) this;
        }

        public Criteria andGovernLawEqualTo(String value) {
            addCriterion("govern_law =", value, "governLaw");
            return (Criteria) this;
        }

        public Criteria andGovernLawNotEqualTo(String value) {
            addCriterion("govern_law <>", value, "governLaw");
            return (Criteria) this;
        }

        public Criteria andGovernLawGreaterThan(String value) {
            addCriterion("govern_law >", value, "governLaw");
            return (Criteria) this;
        }

        public Criteria andGovernLawGreaterThanOrEqualTo(String value) {
            addCriterion("govern_law >=", value, "governLaw");
            return (Criteria) this;
        }

        public Criteria andGovernLawLessThan(String value) {
            addCriterion("govern_law <", value, "governLaw");
            return (Criteria) this;
        }

        public Criteria andGovernLawLessThanOrEqualTo(String value) {
            addCriterion("govern_law <=", value, "governLaw");
            return (Criteria) this;
        }

        public Criteria andGovernLawLike(String value) {
            addCriterion("govern_law like", value, "governLaw");
            return (Criteria) this;
        }

        public Criteria andGovernLawNotLike(String value) {
            addCriterion("govern_law not like", value, "governLaw");
            return (Criteria) this;
        }

        public Criteria andGovernLawIn(List<String> values) {
            addCriterion("govern_law in", values, "governLaw");
            return (Criteria) this;
        }

        public Criteria andGovernLawNotIn(List<String> values) {
            addCriterion("govern_law not in", values, "governLaw");
            return (Criteria) this;
        }

        public Criteria andGovernLawBetween(String value1, String value2) {
            addCriterion("govern_law between", value1, value2, "governLaw");
            return (Criteria) this;
        }

        public Criteria andGovernLawNotBetween(String value1, String value2) {
            addCriterion("govern_law not between", value1, value2, "governLaw");
            return (Criteria) this;
        }

        public Criteria andTrailExplainIsNull() {
            addCriterion("trail_explain is null");
            return (Criteria) this;
        }

        public Criteria andTrailExplainIsNotNull() {
            addCriterion("trail_explain is not null");
            return (Criteria) this;
        }

        public Criteria andTrailExplainEqualTo(String value) {
            addCriterion("trail_explain =", value, "trailExplain");
            return (Criteria) this;
        }

        public Criteria andTrailExplainNotEqualTo(String value) {
            addCriterion("trail_explain <>", value, "trailExplain");
            return (Criteria) this;
        }

        public Criteria andTrailExplainGreaterThan(String value) {
            addCriterion("trail_explain >", value, "trailExplain");
            return (Criteria) this;
        }

        public Criteria andTrailExplainGreaterThanOrEqualTo(String value) {
            addCriterion("trail_explain >=", value, "trailExplain");
            return (Criteria) this;
        }

        public Criteria andTrailExplainLessThan(String value) {
            addCriterion("trail_explain <", value, "trailExplain");
            return (Criteria) this;
        }

        public Criteria andTrailExplainLessThanOrEqualTo(String value) {
            addCriterion("trail_explain <=", value, "trailExplain");
            return (Criteria) this;
        }

        public Criteria andTrailExplainLike(String value) {
            addCriterion("trail_explain like", value, "trailExplain");
            return (Criteria) this;
        }

        public Criteria andTrailExplainNotLike(String value) {
            addCriterion("trail_explain not like", value, "trailExplain");
            return (Criteria) this;
        }

        public Criteria andTrailExplainIn(List<String> values) {
            addCriterion("trail_explain in", values, "trailExplain");
            return (Criteria) this;
        }

        public Criteria andTrailExplainNotIn(List<String> values) {
            addCriterion("trail_explain not in", values, "trailExplain");
            return (Criteria) this;
        }

        public Criteria andTrailExplainBetween(String value1, String value2) {
            addCriterion("trail_explain between", value1, value2, "trailExplain");
            return (Criteria) this;
        }

        public Criteria andTrailExplainNotBetween(String value1, String value2) {
            addCriterion("trail_explain not between", value1, value2, "trailExplain");
            return (Criteria) this;
        }

        public Criteria andTitleLawIsNull() {
            addCriterion("title_law is null");
            return (Criteria) this;
        }

        public Criteria andTitleLawIsNotNull() {
            addCriterion("title_law is not null");
            return (Criteria) this;
        }

        public Criteria andTitleLawEqualTo(String value) {
            addCriterion("title_law =", value, "titleLaw");
            return (Criteria) this;
        }

        public Criteria andTitleLawNotEqualTo(String value) {
            addCriterion("title_law <>", value, "titleLaw");
            return (Criteria) this;
        }

        public Criteria andTitleLawGreaterThan(String value) {
            addCriterion("title_law >", value, "titleLaw");
            return (Criteria) this;
        }

        public Criteria andTitleLawGreaterThanOrEqualTo(String value) {
            addCriterion("title_law >=", value, "titleLaw");
            return (Criteria) this;
        }

        public Criteria andTitleLawLessThan(String value) {
            addCriterion("title_law <", value, "titleLaw");
            return (Criteria) this;
        }

        public Criteria andTitleLawLessThanOrEqualTo(String value) {
            addCriterion("title_law <=", value, "titleLaw");
            return (Criteria) this;
        }

        public Criteria andTitleLawLike(String value) {
            addCriterion("title_law like", value, "titleLaw");
            return (Criteria) this;
        }

        public Criteria andTitleLawNotLike(String value) {
            addCriterion("title_law not like", value, "titleLaw");
            return (Criteria) this;
        }

        public Criteria andTitleLawIn(List<String> values) {
            addCriterion("title_law in", values, "titleLaw");
            return (Criteria) this;
        }

        public Criteria andTitleLawNotIn(List<String> values) {
            addCriterion("title_law not in", values, "titleLaw");
            return (Criteria) this;
        }

        public Criteria andTitleLawBetween(String value1, String value2) {
            addCriterion("title_law between", value1, value2, "titleLaw");
            return (Criteria) this;
        }

        public Criteria andTitleLawNotBetween(String value1, String value2) {
            addCriterion("title_law not between", value1, value2, "titleLaw");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(String value) {
            addCriterion("parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(String value) {
            addCriterion("parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(String value) {
            addCriterion("parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(String value) {
            addCriterion("parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(String value) {
            addCriterion("parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLike(String value) {
            addCriterion("parent_id like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotLike(String value) {
            addCriterion("parent_id not like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<String> values) {
            addCriterion("parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<String> values) {
            addCriterion("parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(String value1, String value2) {
            addCriterion("parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(String value1, String value2) {
            addCriterion("parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andModifyTypeIsNull() {
            addCriterion("modify_type is null");
            return (Criteria) this;
        }

        public Criteria andModifyTypeIsNotNull() {
            addCriterion("modify_type is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTypeEqualTo(Integer value) {
            addCriterion("modify_type =", value, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeNotEqualTo(Integer value) {
            addCriterion("modify_type <>", value, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeGreaterThan(Integer value) {
            addCriterion("modify_type >", value, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("modify_type >=", value, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeLessThan(Integer value) {
            addCriterion("modify_type <", value, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeLessThanOrEqualTo(Integer value) {
            addCriterion("modify_type <=", value, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeIn(List<Integer> values) {
            addCriterion("modify_type in", values, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeNotIn(List<Integer> values) {
            addCriterion("modify_type not in", values, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeBetween(Integer value1, Integer value2) {
            addCriterion("modify_type between", value1, value2, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("modify_type not between", value1, value2, "modifyType");
            return (Criteria) this;
        }

        public Criteria andSourceIdIsNull() {
            addCriterion("source_id is null");
            return (Criteria) this;
        }

        public Criteria andSourceIdIsNotNull() {
            addCriterion("source_id is not null");
            return (Criteria) this;
        }

        public Criteria andSourceIdEqualTo(String value) {
            addCriterion("source_id =", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotEqualTo(String value) {
            addCriterion("source_id <>", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdGreaterThan(String value) {
            addCriterion("source_id >", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdGreaterThanOrEqualTo(String value) {
            addCriterion("source_id >=", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdLessThan(String value) {
            addCriterion("source_id <", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdLessThanOrEqualTo(String value) {
            addCriterion("source_id <=", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdLike(String value) {
            addCriterion("source_id like", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotLike(String value) {
            addCriterion("source_id not like", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdIn(List<String> values) {
            addCriterion("source_id in", values, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotIn(List<String> values) {
            addCriterion("source_id not in", values, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdBetween(String value1, String value2) {
            addCriterion("source_id between", value1, value2, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotBetween(String value1, String value2) {
            addCriterion("source_id not between", value1, value2, "sourceId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_guide_law
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_guide_law
         *
         * @mbg.generated
         */
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_guide_law
     *
     * @mbg.generated
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_guide_law
         *
         * @mbg.generated
         */
        private static final long serialVersionUID = 1L;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}