package com.ocp.rabbit.middleware.orm.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/** 
 * 用于操作表:infopoint
 */
public class InfoPointExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table infopoint
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table infopoint
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table infopoint
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table infopoint
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table infopoint
     *
     * @mbg.generated
     */
    private int startNum = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table infopoint
     *
     * @mbg.generated
     */
    private int endNum = 10;

    /**
     *
     * @mbg.generated
     */
    public InfoPointExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *
     * @mbg.generated
     */
    public void setStartNum(int startNum) {
        this.startNum=startNum;
    }

    /**
     *
     * @mbg.generated
     */
    public int getStartNum() {
        return startNum;
    }

    /**
     *
     * @mbg.generated
     */
    public void setEndNum(int endNum) {
        this.endNum=endNum;
    }

    /**
     *
     * @mbg.generated
     */
    public int getEndNum() {
        return endNum - startNum;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table infopoint
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table infopoint
         *
         * @mbg.generated
         */
        private static final long serialVersionUID = 1L;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrgIsNull() {
            addCriterion("org is null");
            return (Criteria) this;
        }

        public Criteria andOrgIsNotNull() {
            addCriterion("org is not null");
            return (Criteria) this;
        }

        public Criteria andOrgEqualTo(String value) {
            addCriterion("org =", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgNotEqualTo(String value) {
            addCriterion("org <>", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgGreaterThan(String value) {
            addCriterion("org >", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgGreaterThanOrEqualTo(String value) {
            addCriterion("org >=", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgLessThan(String value) {
            addCriterion("org <", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgLessThanOrEqualTo(String value) {
            addCriterion("org <=", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgLike(String value) {
            addCriterion("org like", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgNotLike(String value) {
            addCriterion("org not like", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgIn(List<String> values) {
            addCriterion("org in", values, "org");
            return (Criteria) this;
        }

        public Criteria andOrgNotIn(List<String> values) {
            addCriterion("org not in", values, "org");
            return (Criteria) this;
        }

        public Criteria andOrgBetween(String value1, String value2) {
            addCriterion("org between", value1, value2, "org");
            return (Criteria) this;
        }

        public Criteria andOrgNotBetween(String value1, String value2) {
            addCriterion("org not between", value1, value2, "org");
            return (Criteria) this;
        }

        public Criteria andDoctypeIsNull() {
            addCriterion("docType is null");
            return (Criteria) this;
        }

        public Criteria andDoctypeIsNotNull() {
            addCriterion("docType is not null");
            return (Criteria) this;
        }

        public Criteria andDoctypeEqualTo(String value) {
            addCriterion("docType =", value, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeNotEqualTo(String value) {
            addCriterion("docType <>", value, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeGreaterThan(String value) {
            addCriterion("docType >", value, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeGreaterThanOrEqualTo(String value) {
            addCriterion("docType >=", value, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeLessThan(String value) {
            addCriterion("docType <", value, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeLessThanOrEqualTo(String value) {
            addCriterion("docType <=", value, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeLike(String value) {
            addCriterion("docType like", value, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeNotLike(String value) {
            addCriterion("docType not like", value, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeIn(List<String> values) {
            addCriterion("docType in", values, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeNotIn(List<String> values) {
            addCriterion("docType not in", values, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeBetween(String value1, String value2) {
            addCriterion("docType between", value1, value2, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeNotBetween(String value1, String value2) {
            addCriterion("docType not between", value1, value2, "doctype");
            return (Criteria) this;
        }

        public Criteria andAyIsNull() {
            addCriterion("ay is null");
            return (Criteria) this;
        }

        public Criteria andAyIsNotNull() {
            addCriterion("ay is not null");
            return (Criteria) this;
        }

        public Criteria andAyEqualTo(String value) {
            addCriterion("ay =", value, "ay");
            return (Criteria) this;
        }

        public Criteria andAyNotEqualTo(String value) {
            addCriterion("ay <>", value, "ay");
            return (Criteria) this;
        }

        public Criteria andAyGreaterThan(String value) {
            addCriterion("ay >", value, "ay");
            return (Criteria) this;
        }

        public Criteria andAyGreaterThanOrEqualTo(String value) {
            addCriterion("ay >=", value, "ay");
            return (Criteria) this;
        }

        public Criteria andAyLessThan(String value) {
            addCriterion("ay <", value, "ay");
            return (Criteria) this;
        }

        public Criteria andAyLessThanOrEqualTo(String value) {
            addCriterion("ay <=", value, "ay");
            return (Criteria) this;
        }

        public Criteria andAyLike(String value) {
            addCriterion("ay like", value, "ay");
            return (Criteria) this;
        }

        public Criteria andAyNotLike(String value) {
            addCriterion("ay not like", value, "ay");
            return (Criteria) this;
        }

        public Criteria andAyIn(List<String> values) {
            addCriterion("ay in", values, "ay");
            return (Criteria) this;
        }

        public Criteria andAyNotIn(List<String> values) {
            addCriterion("ay not in", values, "ay");
            return (Criteria) this;
        }

        public Criteria andAyBetween(String value1, String value2) {
            addCriterion("ay between", value1, value2, "ay");
            return (Criteria) this;
        }

        public Criteria andAyNotBetween(String value1, String value2) {
            addCriterion("ay not between", value1, value2, "ay");
            return (Criteria) this;
        }

        public Criteria andMajorayIsNull() {
            addCriterion("majorAy is null");
            return (Criteria) this;
        }

        public Criteria andMajorayIsNotNull() {
            addCriterion("majorAy is not null");
            return (Criteria) this;
        }

        public Criteria andMajorayEqualTo(String value) {
            addCriterion("majorAy =", value, "majoray");
            return (Criteria) this;
        }

        public Criteria andMajorayNotEqualTo(String value) {
            addCriterion("majorAy <>", value, "majoray");
            return (Criteria) this;
        }

        public Criteria andMajorayGreaterThan(String value) {
            addCriterion("majorAy >", value, "majoray");
            return (Criteria) this;
        }

        public Criteria andMajorayGreaterThanOrEqualTo(String value) {
            addCriterion("majorAy >=", value, "majoray");
            return (Criteria) this;
        }

        public Criteria andMajorayLessThan(String value) {
            addCriterion("majorAy <", value, "majoray");
            return (Criteria) this;
        }

        public Criteria andMajorayLessThanOrEqualTo(String value) {
            addCriterion("majorAy <=", value, "majoray");
            return (Criteria) this;
        }

        public Criteria andMajorayLike(String value) {
            addCriterion("majorAy like", value, "majoray");
            return (Criteria) this;
        }

        public Criteria andMajorayNotLike(String value) {
            addCriterion("majorAy not like", value, "majoray");
            return (Criteria) this;
        }

        public Criteria andMajorayIn(List<String> values) {
            addCriterion("majorAy in", values, "majoray");
            return (Criteria) this;
        }

        public Criteria andMajorayNotIn(List<String> values) {
            addCriterion("majorAy not in", values, "majoray");
            return (Criteria) this;
        }

        public Criteria andMajorayBetween(String value1, String value2) {
            addCriterion("majorAy between", value1, value2, "majoray");
            return (Criteria) this;
        }

        public Criteria andMajorayNotBetween(String value1, String value2) {
            addCriterion("majorAy not between", value1, value2, "majoray");
            return (Criteria) this;
        }

        public Criteria andVariableIsNull() {
            addCriterion("variable is null");
            return (Criteria) this;
        }

        public Criteria andVariableIsNotNull() {
            addCriterion("variable is not null");
            return (Criteria) this;
        }

        public Criteria andVariableEqualTo(String value) {
            addCriterion("variable =", value, "variable");
            return (Criteria) this;
        }

        public Criteria andVariableNotEqualTo(String value) {
            addCriterion("variable <>", value, "variable");
            return (Criteria) this;
        }

        public Criteria andVariableGreaterThan(String value) {
            addCriterion("variable >", value, "variable");
            return (Criteria) this;
        }

        public Criteria andVariableGreaterThanOrEqualTo(String value) {
            addCriterion("variable >=", value, "variable");
            return (Criteria) this;
        }

        public Criteria andVariableLessThan(String value) {
            addCriterion("variable <", value, "variable");
            return (Criteria) this;
        }

        public Criteria andVariableLessThanOrEqualTo(String value) {
            addCriterion("variable <=", value, "variable");
            return (Criteria) this;
        }

        public Criteria andVariableLike(String value) {
            addCriterion("variable like", value, "variable");
            return (Criteria) this;
        }

        public Criteria andVariableNotLike(String value) {
            addCriterion("variable not like", value, "variable");
            return (Criteria) this;
        }

        public Criteria andVariableIn(List<String> values) {
            addCriterion("variable in", values, "variable");
            return (Criteria) this;
        }

        public Criteria andVariableNotIn(List<String> values) {
            addCriterion("variable not in", values, "variable");
            return (Criteria) this;
        }

        public Criteria andVariableBetween(String value1, String value2) {
            addCriterion("variable between", value1, value2, "variable");
            return (Criteria) this;
        }

        public Criteria andVariableNotBetween(String value1, String value2) {
            addCriterion("variable not between", value1, value2, "variable");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andReturntypeIsNull() {
            addCriterion("returnType is null");
            return (Criteria) this;
        }

        public Criteria andReturntypeIsNotNull() {
            addCriterion("returnType is not null");
            return (Criteria) this;
        }

        public Criteria andReturntypeEqualTo(String value) {
            addCriterion("returnType =", value, "returntype");
            return (Criteria) this;
        }

        public Criteria andReturntypeNotEqualTo(String value) {
            addCriterion("returnType <>", value, "returntype");
            return (Criteria) this;
        }

        public Criteria andReturntypeGreaterThan(String value) {
            addCriterion("returnType >", value, "returntype");
            return (Criteria) this;
        }

        public Criteria andReturntypeGreaterThanOrEqualTo(String value) {
            addCriterion("returnType >=", value, "returntype");
            return (Criteria) this;
        }

        public Criteria andReturntypeLessThan(String value) {
            addCriterion("returnType <", value, "returntype");
            return (Criteria) this;
        }

        public Criteria andReturntypeLessThanOrEqualTo(String value) {
            addCriterion("returnType <=", value, "returntype");
            return (Criteria) this;
        }

        public Criteria andReturntypeLike(String value) {
            addCriterion("returnType like", value, "returntype");
            return (Criteria) this;
        }

        public Criteria andReturntypeNotLike(String value) {
            addCriterion("returnType not like", value, "returntype");
            return (Criteria) this;
        }

        public Criteria andReturntypeIn(List<String> values) {
            addCriterion("returnType in", values, "returntype");
            return (Criteria) this;
        }

        public Criteria andReturntypeNotIn(List<String> values) {
            addCriterion("returnType not in", values, "returntype");
            return (Criteria) this;
        }

        public Criteria andReturntypeBetween(String value1, String value2) {
            addCriterion("returnType between", value1, value2, "returntype");
            return (Criteria) this;
        }

        public Criteria andReturntypeNotBetween(String value1, String value2) {
            addCriterion("returnType not between", value1, value2, "returntype");
            return (Criteria) this;
        }

        public Criteria andJsonpathIsNull() {
            addCriterion("jsonPath is null");
            return (Criteria) this;
        }

        public Criteria andJsonpathIsNotNull() {
            addCriterion("jsonPath is not null");
            return (Criteria) this;
        }

        public Criteria andJsonpathEqualTo(String value) {
            addCriterion("jsonPath =", value, "jsonpath");
            return (Criteria) this;
        }

        public Criteria andJsonpathNotEqualTo(String value) {
            addCriterion("jsonPath <>", value, "jsonpath");
            return (Criteria) this;
        }

        public Criteria andJsonpathGreaterThan(String value) {
            addCriterion("jsonPath >", value, "jsonpath");
            return (Criteria) this;
        }

        public Criteria andJsonpathGreaterThanOrEqualTo(String value) {
            addCriterion("jsonPath >=", value, "jsonpath");
            return (Criteria) this;
        }

        public Criteria andJsonpathLessThan(String value) {
            addCriterion("jsonPath <", value, "jsonpath");
            return (Criteria) this;
        }

        public Criteria andJsonpathLessThanOrEqualTo(String value) {
            addCriterion("jsonPath <=", value, "jsonpath");
            return (Criteria) this;
        }

        public Criteria andJsonpathLike(String value) {
            addCriterion("jsonPath like", value, "jsonpath");
            return (Criteria) this;
        }

        public Criteria andJsonpathNotLike(String value) {
            addCriterion("jsonPath not like", value, "jsonpath");
            return (Criteria) this;
        }

        public Criteria andJsonpathIn(List<String> values) {
            addCriterion("jsonPath in", values, "jsonpath");
            return (Criteria) this;
        }

        public Criteria andJsonpathNotIn(List<String> values) {
            addCriterion("jsonPath not in", values, "jsonpath");
            return (Criteria) this;
        }

        public Criteria andJsonpathBetween(String value1, String value2) {
            addCriterion("jsonPath between", value1, value2, "jsonpath");
            return (Criteria) this;
        }

        public Criteria andJsonpathNotBetween(String value1, String value2) {
            addCriterion("jsonPath not between", value1, value2, "jsonpath");
            return (Criteria) this;
        }

        public Criteria andValuedomainIsNull() {
            addCriterion("valueDomain is null");
            return (Criteria) this;
        }

        public Criteria andValuedomainIsNotNull() {
            addCriterion("valueDomain is not null");
            return (Criteria) this;
        }

        public Criteria andValuedomainEqualTo(String value) {
            addCriterion("valueDomain =", value, "valuedomain");
            return (Criteria) this;
        }

        public Criteria andValuedomainNotEqualTo(String value) {
            addCriterion("valueDomain <>", value, "valuedomain");
            return (Criteria) this;
        }

        public Criteria andValuedomainGreaterThan(String value) {
            addCriterion("valueDomain >", value, "valuedomain");
            return (Criteria) this;
        }

        public Criteria andValuedomainGreaterThanOrEqualTo(String value) {
            addCriterion("valueDomain >=", value, "valuedomain");
            return (Criteria) this;
        }

        public Criteria andValuedomainLessThan(String value) {
            addCriterion("valueDomain <", value, "valuedomain");
            return (Criteria) this;
        }

        public Criteria andValuedomainLessThanOrEqualTo(String value) {
            addCriterion("valueDomain <=", value, "valuedomain");
            return (Criteria) this;
        }

        public Criteria andValuedomainLike(String value) {
            addCriterion("valueDomain like", value, "valuedomain");
            return (Criteria) this;
        }

        public Criteria andValuedomainNotLike(String value) {
            addCriterion("valueDomain not like", value, "valuedomain");
            return (Criteria) this;
        }

        public Criteria andValuedomainIn(List<String> values) {
            addCriterion("valueDomain in", values, "valuedomain");
            return (Criteria) this;
        }

        public Criteria andValuedomainNotIn(List<String> values) {
            addCriterion("valueDomain not in", values, "valuedomain");
            return (Criteria) this;
        }

        public Criteria andValuedomainBetween(String value1, String value2) {
            addCriterion("valueDomain between", value1, value2, "valuedomain");
            return (Criteria) this;
        }

        public Criteria andValuedomainNotBetween(String value1, String value2) {
            addCriterion("valueDomain not between", value1, value2, "valuedomain");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andRIsNull() {
            addCriterion("r is null");
            return (Criteria) this;
        }

        public Criteria andRIsNotNull() {
            addCriterion("r is not null");
            return (Criteria) this;
        }

        public Criteria andREqualTo(String value) {
            addCriterion("r =", value, "r");
            return (Criteria) this;
        }

        public Criteria andRNotEqualTo(String value) {
            addCriterion("r <>", value, "r");
            return (Criteria) this;
        }

        public Criteria andRGreaterThan(String value) {
            addCriterion("r >", value, "r");
            return (Criteria) this;
        }

        public Criteria andRGreaterThanOrEqualTo(String value) {
            addCriterion("r >=", value, "r");
            return (Criteria) this;
        }

        public Criteria andRLessThan(String value) {
            addCriterion("r <", value, "r");
            return (Criteria) this;
        }

        public Criteria andRLessThanOrEqualTo(String value) {
            addCriterion("r <=", value, "r");
            return (Criteria) this;
        }

        public Criteria andRLike(String value) {
            addCriterion("r like", value, "r");
            return (Criteria) this;
        }

        public Criteria andRNotLike(String value) {
            addCriterion("r not like", value, "r");
            return (Criteria) this;
        }

        public Criteria andRIn(List<String> values) {
            addCriterion("r in", values, "r");
            return (Criteria) this;
        }

        public Criteria andRNotIn(List<String> values) {
            addCriterion("r not in", values, "r");
            return (Criteria) this;
        }

        public Criteria andRBetween(String value1, String value2) {
            addCriterion("r between", value1, value2, "r");
            return (Criteria) this;
        }

        public Criteria andRNotBetween(String value1, String value2) {
            addCriterion("r not between", value1, value2, "r");
            return (Criteria) this;
        }

        public Criteria andWIsNull() {
            addCriterion("w is null");
            return (Criteria) this;
        }

        public Criteria andWIsNotNull() {
            addCriterion("w is not null");
            return (Criteria) this;
        }

        public Criteria andWEqualTo(String value) {
            addCriterion("w =", value, "w");
            return (Criteria) this;
        }

        public Criteria andWNotEqualTo(String value) {
            addCriterion("w <>", value, "w");
            return (Criteria) this;
        }

        public Criteria andWGreaterThan(String value) {
            addCriterion("w >", value, "w");
            return (Criteria) this;
        }

        public Criteria andWGreaterThanOrEqualTo(String value) {
            addCriterion("w >=", value, "w");
            return (Criteria) this;
        }

        public Criteria andWLessThan(String value) {
            addCriterion("w <", value, "w");
            return (Criteria) this;
        }

        public Criteria andWLessThanOrEqualTo(String value) {
            addCriterion("w <=", value, "w");
            return (Criteria) this;
        }

        public Criteria andWLike(String value) {
            addCriterion("w like", value, "w");
            return (Criteria) this;
        }

        public Criteria andWNotLike(String value) {
            addCriterion("w not like", value, "w");
            return (Criteria) this;
        }

        public Criteria andWIn(List<String> values) {
            addCriterion("w in", values, "w");
            return (Criteria) this;
        }

        public Criteria andWNotIn(List<String> values) {
            addCriterion("w not in", values, "w");
            return (Criteria) this;
        }

        public Criteria andWBetween(String value1, String value2) {
            addCriterion("w between", value1, value2, "w");
            return (Criteria) this;
        }

        public Criteria andWNotBetween(String value1, String value2) {
            addCriterion("w not between", value1, value2, "w");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table infopoint
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table infopoint
         *
         * @mbg.generated
         */
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table infopoint
     *
     * @mbg.generated
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table infopoint
         *
         * @mbg.generated
         */
        private static final long serialVersionUID = 1L;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}