package com.ocp.rabbit.middleware.orm.model;

import java.io.Serializable;

/** 
 * 用于操作表:infopoint
 * 功能描述:
 */
public class InfoPoint extends BaseModel implements Serializable {
    /**
     * 组织机构(court/procuratorate)
     *
     * @mbg.generated
     */
    private String org;

    /**
     * 文书类型
     *
     * @mbg.generated
     */
    private String doctype;

    /**
     * 案由
     *
     * @mbg.generated
     */
    private String ay;

    /**
     * 案由大类
     *
     * @mbg.generated
     */
    private String majoray;

    /**
     * 信息点变量名
     *
     * @mbg.generated
     */
    private String variable;

    /**
     * 信息点名
     *
     * @mbg.generated
     */
    private String name;

    /**
     * 返回类型
     *
     * @mbg.generated
     */
    private String returntype;

    /**
     * json路径
     *
     * @mbg.generated
     */
    private String jsonpath;

    /**
     * 取值范围
     *
     * @mbg.generated
     */
    private String valuedomain;

    /**
     * 备注
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * 版本
     *
     * @mbg.generated
     */
    private String version;

    /**
     * 是否可查看
     *
     * @mbg.generated
     */
    private String r;

    /**
     * 是否可直接抽取
     *
     * @mbg.generated
     */
    private String w;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table infopoint
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infopoint.org
     *
     * @return the value of infopoint.org
     *
     * @mbg.generated
     */
    public String getOrg() {
        return org;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infopoint.org
     *
     * @param org the value for infopoint.org
     *
     * @mbg.generated
     */
    public void setOrg(String org) {
        this.org = org;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infopoint.docType
     *
     * @return the value of infopoint.docType
     *
     * @mbg.generated
     */
    public String getDoctype() {
        return doctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infopoint.docType
     *
     * @param doctype the value for infopoint.docType
     *
     * @mbg.generated
     */
    public void setDoctype(String doctype) {
        this.doctype = doctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infopoint.ay
     *
     * @return the value of infopoint.ay
     *
     * @mbg.generated
     */
    public String getAy() {
        return ay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infopoint.ay
     *
     * @param ay the value for infopoint.ay
     *
     * @mbg.generated
     */
    public void setAy(String ay) {
        this.ay = ay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infopoint.majorAy
     *
     * @return the value of infopoint.majorAy
     *
     * @mbg.generated
     */
    public String getMajoray() {
        return majoray;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infopoint.majorAy
     *
     * @param majoray the value for infopoint.majorAy
     *
     * @mbg.generated
     */
    public void setMajoray(String majoray) {
        this.majoray = majoray;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infopoint.variable
     *
     * @return the value of infopoint.variable
     *
     * @mbg.generated
     */
    public String getVariable() {
        return variable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infopoint.variable
     *
     * @param variable the value for infopoint.variable
     *
     * @mbg.generated
     */
    public void setVariable(String variable) {
        this.variable = variable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infopoint.name
     *
     * @return the value of infopoint.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infopoint.name
     *
     * @param name the value for infopoint.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infopoint.returnType
     *
     * @return the value of infopoint.returnType
     *
     * @mbg.generated
     */
    public String getReturntype() {
        return returntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infopoint.returnType
     *
     * @param returntype the value for infopoint.returnType
     *
     * @mbg.generated
     */
    public void setReturntype(String returntype) {
        this.returntype = returntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infopoint.jsonPath
     *
     * @return the value of infopoint.jsonPath
     *
     * @mbg.generated
     */
    public String getJsonpath() {
        return jsonpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infopoint.jsonPath
     *
     * @param jsonpath the value for infopoint.jsonPath
     *
     * @mbg.generated
     */
    public void setJsonpath(String jsonpath) {
        this.jsonpath = jsonpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infopoint.valueDomain
     *
     * @return the value of infopoint.valueDomain
     *
     * @mbg.generated
     */
    public String getValuedomain() {
        return valuedomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infopoint.valueDomain
     *
     * @param valuedomain the value for infopoint.valueDomain
     *
     * @mbg.generated
     */
    public void setValuedomain(String valuedomain) {
        this.valuedomain = valuedomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infopoint.remark
     *
     * @return the value of infopoint.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infopoint.remark
     *
     * @param remark the value for infopoint.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infopoint.version
     *
     * @return the value of infopoint.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infopoint.version
     *
     * @param version the value for infopoint.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infopoint.r
     *
     * @return the value of infopoint.r
     *
     * @mbg.generated
     */
    public String getR() {
        return r;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infopoint.r
     *
     * @param r the value for infopoint.r
     *
     * @mbg.generated
     */
    public void setR(String r) {
        this.r = r;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infopoint.w
     *
     * @return the value of infopoint.w
     *
     * @mbg.generated
     */
    public String getW() {
        return w;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infopoint.w
     *
     * @param w the value for infopoint.w
     *
     * @mbg.generated
     */
    public void setW(String w) {
        this.w = w;
    }
}