/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ocp_ai_engine_vision_ocr_OCRJNI */

#ifndef _Included_com_ocp_ai_engine_vision_ocr_OCRJNI
#define _Included_com_ocp_ai_engine_vision_ocr_OCRJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ocp_ai_engine_vision_ocr_OCRJNI
 * Method:    convert
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ocp_ai_engine_vision_ocr_OCRJNI_convert
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
